pipeline{
    agent any
    stages{
        stage('Remove image'){
         steps{
            
             sh 'docker rm app-java --force'
         }
    }
    stage('Remove image'){
       steps{
            sh  'docker rmi app-java --force'
                       
            }

        }    
     
    }
    
}

