pipeline {
    agent any
    stages {
        stage ('Run container') {
            steps {
                sh 'docker run --restart unless-stopped -dti -p 8080:8080 --name app-java app-java'

             }
         }
         stage('test'){
            steps{
                sh 'docker exec app-java curl localhost:8080/actuator/health'
            }
        }
    }

}
